name: Continuous Preview Release 

on:
  push:
    branches:
      - main

jobs:
  check:
    # First, trigger a permissions check on the user approving the pull request.
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result }}
    steps:
      - name: Check permissions
        id: checkPermissions
        uses: actions-cool/check-user-permission@v2
        with:
          require: "write"

  publish:
    needs: check
    # Publish the preview package only if the permissions check passed.
    if: needs.check.outputs.has-permissions == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - run: corepack enable
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: "pnpm"

      # - name: Install dependencies
      #   run: pnpm install

      # - run: pnpm dlx pkg-pr-new publish

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run pkg-pr-new for all packages
        run: npx pkg-pr-new@0.0 publish './packages/*' --packageManager=pnpm 


# This workflow is triggered on pushes to the main branch and runs the pkg-pr-new command
# for all packages in the monorepo to generate preview release pull requests.
# name: Preview Release

# on:
  # push:
    # branches:
      # - main

# jobs:
#   preview-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm install

#       - name: Run pkg-pr-new for all packages
#         run: npx pkg-pr-new